name: APM-R128gain scraper
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  buildAPK:
    runs-on: ubuntu-latest
    name: scraper
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: python version_bump.py
        run: |
          python scraper.py ${{ secrets.VERCEL_GET_URL }}

      - name: commit
        run: |
          git config --global user.email lovegaoshi@gaoshi.com
          git config --global user.name lovegaoshi
          git commit -m "chore: weekly r128gain scrape" -a

      - name: Push changes to master
        uses: ad-m/github-push-action@master
